planificador: consola.c logger_planificador.c planificador.c   ../socket/operacion.c ../socket/socket.c ../socket/common.c
	gcc -o planificador consola.c logger_planificador.c planificador.c   ../socket/operacion.c ../socket/socket.c ../socket/common.c -I"../socket" -I"../" -L/usr/lib -lcommons -lpthread -lreadline

