esi: esi.c ../parsi/src/parsi/parser.c ../socket/operacion.c ../socket/socket.c ../socket/common.c 
	gcc -o esi esi.c ../parsi/src/parsi/parser.c ../socket/operacion.c ../socket/socket.c ../socket/common.c -I"./socket" -I"./" -L/usr/lib -lcommons -lpthread -lreadline
