coordinador: configuracion.c  coordinador.c  logger_coordinador.c  tabla_instancias.c conexiones.c ../socket/operacion.c ../socket/socket.c ../socket/common.c 
	gcc -o coordinador configuracion.c  coordinador.c  logger_coordinador.c  tabla_instancias.c conexiones.c ../socket/operacion.c ../socket/socket.c ../socket/common.c -I"../socket" -I"./" -L/usr/lib -lcommons -lpthread
